baseURL = "https://www.fableford.com"
languageCode = "en-us"
title = "Fableford"
theme = "fableford"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
    
  [[menu.main]]
    identifier = "learn-more-parent"
    name = "Learn More"
    url = "#"
    weight = 2
    
  [[menu.main]]
    identifier = "about"
    name = "About Fableford"
    url = "/learn-more/"
    parent = "learn-more-parent"
    weight = 1
    
  [[menu.main]]
    identifier = "for-writers"
    name = "For Writers"
    url = "/for-writers/"
    parent = "learn-more-parent"
    weight = 2
    
  [[menu.main]]
    identifier = "for-readers"
    name = "For Readers"
    url = "/for-readers/"
    parent = "learn-more-parent"
    weight = 3
    

[params]
  description = "Fableford is a collaborative storytelling platform where writers create and publish interconnected stories through their own characters in a shared world."
  
  [params.footer]
    [[params.footer.links]]
      icon = "fab fa-discord"
      text = "Join our Discord"
      url = "https://discord.gg/6vmx7u2es5"
