name: Deploy to Google Cloud Storage

on:
  push:
    branches:
      - main # Or your main branch
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: fableford

      - name: Deploy to GCS
        run: |
          gsutil -m rm -r gs://${{ vars.GCS_BUCKET_NAME }}/** # remove existing files
          gsutil -m cp -r public/* gs://${{ vars.GCS_BUCKET_NAME }}/ # copy only contents of public directory