name: Deploy to Google Cloud Storage

on:
  push:
    branches:
      - main # Or your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: fableford



      - name: Deploy to GCS
        run: |
          # Debug the bucket name variable
          echo "GCS Bucket Name: ${{ vars.GCS_BUCKET_NAME }}"
          
          # Check if the bucket exists first
          if gsutil ls -b gs://${{ vars.GCS_BUCKET_NAME }}/ &>/dev/null; then
            echo "Bucket exists, proceeding with deployment"
            # Remove existing files (only if bucket exists)
            gsutil -m rm -r gs://${{ vars.GCS_BUCKET_NAME }}/**
          else
            echo "Bucket doesn't exist or is inaccessible. Check your bucket name and permissions."
            echo "Creating bucket if it doesn't exist"
            gsutil mb -p fableford gs://${{ vars.GCS_BUCKET_NAME }}/
          fi
          
          # Copy new files
          gsutil -m cp -r public/* gs://${{ vars.GCS_BUCKET_NAME }}/
          
          # Make all files public
          gsutil acl ch -r -u allUsers:R gs://${{ vars.GCS_BUCKET_NAME }}/